package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppInvite generated by hbm2java
 */
@Entity
@Table(name = "app_invite", schema = "unipointmain")
public class AppInvite implements java.io.Serializable {

	private long inviteId;
	private MerchantUser merchantUserByAddedByRef;
	private MerchantUser merchantUserByLastModifiedByRef;
	private UnipointCustomerProfile unipointCustomerProfile;
	private String datetimeInvited;
	private String contactName;
	private BigDecimal contactPhoneNumber;
	private String statusInstalled;
	private String areUnipointsAwarded;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public AppInvite() {
	}

	public AppInvite(long inviteId) {
		this.inviteId = inviteId;
	}

	public AppInvite(long inviteId, MerchantUser merchantUserByAddedByRef, MerchantUser merchantUserByLastModifiedByRef,
			UnipointCustomerProfile unipointCustomerProfile, String datetimeInvited, String contactName,
			BigDecimal contactPhoneNumber, String statusInstalled, String areUnipointsAwarded, String addedDateTime,
			String lastModifiedDateTime, String lastModifiedFields) {
		this.inviteId = inviteId;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.datetimeInvited = datetimeInvited;
		this.contactName = contactName;
		this.contactPhoneNumber = contactPhoneNumber;
		this.statusInstalled = statusInstalled;
		this.areUnipointsAwarded = areUnipointsAwarded;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id

	@Column(name = "invite_id", unique = true, nullable = false)
	public long getInviteId() {
		return this.inviteId;
	}

	public void setInviteId(long inviteId) {
		this.inviteId = inviteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unipoint_customer_ref_id")
	public UnipointCustomerProfile getUnipointCustomerProfile() {
		return this.unipointCustomerProfile;
	}

	public void setUnipointCustomerProfile(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	@Column(name = "datetime_invited", length = 100)
	public String getDatetimeInvited() {
		return this.datetimeInvited;
	}

	public void setDatetimeInvited(String datetimeInvited) {
		this.datetimeInvited = datetimeInvited;
	}

	@Column(name = "contact_name")
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "contact_phone_number", precision = 131089, scale = 0)
	public BigDecimal getContactPhoneNumber() {
		return this.contactPhoneNumber;
	}

	public void setContactPhoneNumber(BigDecimal contactPhoneNumber) {
		this.contactPhoneNumber = contactPhoneNumber;
	}

	@Column(name = "status_installed", length = 5)
	public String getStatusInstalled() {
		return this.statusInstalled;
	}

	public void setStatusInstalled(String statusInstalled) {
		this.statusInstalled = statusInstalled;
	}

	@Column(name = "are_unipoints_awarded", length = 5)
	public String getAreUnipointsAwarded() {
		return this.areUnipointsAwarded;
	}

	public void setAreUnipointsAwarded(String areUnipointsAwarded) {
		this.areUnipointsAwarded = areUnipointsAwarded;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
