package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AssignedCoupons generated by hbm2java
 */
@Entity
@Table(name = "assigned_coupons", schema = "unipointmain")
public class AssignedCoupons implements java.io.Serializable {

	private long assignedid;
	private MerchantUser merchantUserByAddedByRef;
	private MerchantUser merchantUserByLastModifiedByRef;
	private UnipointCustomerProfile unipointCustomerProfile;
	private String assignedDateTime;
	private Long fkAssignedCouponsCouponId;
	private String expiryDate;
	private String redeemed;
	private Long enabled;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public AssignedCoupons() {
	}

	public AssignedCoupons(long assignedid) {
		this.assignedid = assignedid;
	}

	public AssignedCoupons(long assignedid, MerchantUser merchantUserByAddedByRef,
			MerchantUser merchantUserByLastModifiedByRef, UnipointCustomerProfile unipointCustomerProfile,
			String assignedDateTime, Long fkAssignedCouponsCouponId, String expiryDate, String redeemed, Long enabled,
			String addedDateTime, String lastModifiedDateTime, String lastModifiedFields) {
		this.assignedid = assignedid;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.assignedDateTime = assignedDateTime;
		this.fkAssignedCouponsCouponId = fkAssignedCouponsCouponId;
		this.expiryDate = expiryDate;
		this.redeemed = redeemed;
		this.enabled = enabled;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id

	@Column(name = "assignedid", unique = true, nullable = false)
	public long getAssignedid() {
		return this.assignedid;
	}

	public void setAssignedid(long assignedid) {
		this.assignedid = assignedid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unipoint_customer_ref_id")
	public UnipointCustomerProfile getUnipointCustomerProfile() {
		return this.unipointCustomerProfile;
	}

	public void setUnipointCustomerProfile(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	@Column(name = "assigned_date_time", length = 100)
	public String getAssignedDateTime() {
		return this.assignedDateTime;
	}

	public void setAssignedDateTime(String assignedDateTime) {
		this.assignedDateTime = assignedDateTime;
	}

	@Column(name = "fk_assigned_coupons_coupon_id")
	public Long getFkAssignedCouponsCouponId() {
		return this.fkAssignedCouponsCouponId;
	}

	public void setFkAssignedCouponsCouponId(Long fkAssignedCouponsCouponId) {
		this.fkAssignedCouponsCouponId = fkAssignedCouponsCouponId;
	}

	@Column(name = "expiry_date", length = 100)
	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "redeemed", length = 5)
	public String getRedeemed() {
		return this.redeemed;
	}

	public void setRedeemed(String redeemed) {
		this.redeemed = redeemed;
	}

	@Column(name = "enabled")
	public Long getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Long enabled) {
		this.enabled = enabled;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
