package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CardLog generated by hbm2java
 */
@Entity
@Table(name = "card_log", schema = "unipointmain")
public class CardLog implements java.io.Serializable {

	private long cardlogid;
	private Merchant merchant;
	private UnipointCustomerProfile unipointCustomerProfile;
	private String dateTime;
	private String activity;
	private String activityDescription;
	private String cardEnabled;

	public CardLog() {
	}

	public CardLog(long cardlogid, Merchant merchant, UnipointCustomerProfile unipointCustomerProfile) {
		this.cardlogid = cardlogid;
		this.merchant = merchant;
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	public CardLog(long cardlogid, Merchant merchant, UnipointCustomerProfile unipointCustomerProfile, String dateTime,
			String activity, String activityDescription, String cardEnabled) {
		this.cardlogid = cardlogid;
		this.merchant = merchant;
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.dateTime = dateTime;
		this.activity = activity;
		this.activityDescription = activityDescription;
		this.cardEnabled = cardEnabled;
	}

	@Id

	@Column(name = "cardlogid", unique = true, nullable = false)
	public long getCardlogid() {
		return this.cardlogid;
	}

	public void setCardlogid(long cardlogid) {
		this.cardlogid = cardlogid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_ref_id", nullable = false)
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unipoint_customer_ref_id", nullable = false)
	public UnipointCustomerProfile getUnipointCustomerProfile() {
		return this.unipointCustomerProfile;
	}

	public void setUnipointCustomerProfile(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	@Column(name = "date_time", length = 100)
	public String getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "activity", length = 100)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "activity_description", length = 100)
	public String getActivityDescription() {
		return this.activityDescription;
	}

	public void setActivityDescription(String activityDescription) {
		this.activityDescription = activityDescription;
	}

	@Column(name = "card_enabled", length = 5)
	public String getCardEnabled() {
		return this.cardEnabled;
	}

	public void setCardEnabled(String cardEnabled) {
		this.cardEnabled = cardEnabled;
	}

}
