package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Coupons generated by hbm2java
 */
@Entity
@Table(name = "coupons", schema = "unipointmain")
public class Coupons implements java.io.Serializable {

	private long couponid;
	private MerchantUser merchantUser;
	private String addeddatetime;
	private String expirationdate;
	private BigDecimal value;
	private Double currencycode;
	private Long quantityavailable;
	private String available;

	public Coupons() {
	}

	public Coupons(long couponid) {
		this.couponid = couponid;
	}

	public Coupons(long couponid, MerchantUser merchantUser, String addeddatetime, String expirationdate,
			BigDecimal value, Double currencycode, Long quantityavailable, String available) {
		this.couponid = couponid;
		this.merchantUser = merchantUser;
		this.addeddatetime = addeddatetime;
		this.expirationdate = expirationdate;
		this.value = value;
		this.currencycode = currencycode;
		this.quantityavailable = quantityavailable;
		this.available = available;
	}

	@Id

	@Column(name = "couponid", unique = true, nullable = false)
	public long getCouponid() {
		return this.couponid;
	}

	public void setCouponid(long couponid) {
		this.couponid = couponid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "addedby_mechant_user")
	public MerchantUser getMerchantUser() {
		return this.merchantUser;
	}

	public void setMerchantUser(MerchantUser merchantUser) {
		this.merchantUser = merchantUser;
	}

	@Column(name = "addeddatetime", length = 100)
	public String getAddeddatetime() {
		return this.addeddatetime;
	}

	public void setAddeddatetime(String addeddatetime) {
		this.addeddatetime = addeddatetime;
	}

	@Column(name = "expirationdate", length = 100)
	public String getExpirationdate() {
		return this.expirationdate;
	}

	public void setExpirationdate(String expirationdate) {
		this.expirationdate = expirationdate;
	}

	@Column(name = "value", precision = 131089, scale = 0)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Column(name = "currencycode", scale = 0)
	public Double getCurrencycode() {
		return this.currencycode;
	}

	public void setCurrencycode(Double currencycode) {
		this.currencycode = currencycode;
	}

	@Column(name = "quantityavailable")
	public Long getQuantityavailable() {
		return this.quantityavailable;
	}

	public void setQuantityavailable(Long quantityavailable) {
		this.quantityavailable = quantityavailable;
	}

	@Column(name = "available", length = 5)
	public String getAvailable() {
		return this.available;
	}

	public void setAvailable(String available) {
		this.available = available;
	}

}
