package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerRequests generated by hbm2java
 */
@Entity
@Table(name = "customer_requests", schema = "unipointmain")
public class CustomerRequests implements java.io.Serializable {

	private long requestid;
	private Merchant merchant;
	private MerchantUser merchantUser;
	private UnipointCustomerProfile unipointCustomerProfile;
	private Boolean isAccepted;
	private String addedDateTime;
	private String requestedDateTime;

	public CustomerRequests() {
	}

	public CustomerRequests(long requestid) {
		this.requestid = requestid;
	}

	public CustomerRequests(long requestid, Merchant merchant, MerchantUser merchantUser,
			UnipointCustomerProfile unipointCustomerProfile, Boolean isAccepted, String addedDateTime,
			String requestedDateTime) {
		this.requestid = requestid;
		this.merchant = merchant;
		this.merchantUser = merchantUser;
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.isAccepted = isAccepted;
		this.addedDateTime = addedDateTime;
		this.requestedDateTime = requestedDateTime;
	}

	@Id

	@Column(name = "requestid", unique = true, nullable = false)
	public long getRequestid() {
		return this.requestid;
	}

	public void setRequestid(long requestid) {
		this.requestid = requestid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_id")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUser() {
		return this.merchantUser;
	}

	public void setMerchantUser(MerchantUser merchantUser) {
		this.merchantUser = merchantUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unipoint_customer_id")
	public UnipointCustomerProfile getUnipointCustomerProfile() {
		return this.unipointCustomerProfile;
	}

	public void setUnipointCustomerProfile(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	@Column(name = "isaccepted")
	public Boolean getIsAccepted() {
		return this.isAccepted;
	}

	public void setIsAccepted(Boolean isAccepted) {
		this.isAccepted = isAccepted;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "requested_date_time", length = 50)
	public String getRequestedDateTime() {
		return this.requestedDateTime;
	}

	public void setRequestedDateTime(String requestedDateTime) {
		this.requestedDateTime = requestedDateTime;
	}

}
