package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Faq generated by hbm2java
 */
@Entity
@Table(name = "faq", schema = "unipointmain")
public class Faq implements java.io.Serializable {

	private long faqid;
	private Merchant merchant;
	private MerchantUser merchantUserByLastModifiedByRef;
	private MerchantUser merchantUserByAddedByRef;
	private String createdDateTime;
	private String faqTitle;
	private String faqContent;
	private String enabled;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public Faq() {
	}

	public Faq(long faqid, Merchant merchant) {
		this.faqid = faqid;
		this.merchant = merchant;
	}

	public Faq(long faqid, Merchant merchant, MerchantUser merchantUserByLastModifiedByRef,
			MerchantUser merchantUserByAddedByRef, String createdDateTime, String faqTitle, String faqContent,
			String enabled, String addedDateTime, String lastModifiedDateTime, String lastModifiedFields) {
		this.faqid = faqid;
		this.merchant = merchant;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.createdDateTime = createdDateTime;
		this.faqTitle = faqTitle;
		this.faqContent = faqContent;
		this.enabled = enabled;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id

	@Column(name = "faqid", unique = true, nullable = false)
	public long getFaqid() {
		return this.faqid;
	}

	public void setFaqid(long faqid) {
		this.faqid = faqid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_ref_id", nullable = false)
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@Column(name = "created_date_time", length = 100)
	public String getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(String createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "faq_title")
	public String getFaqTitle() {
		return this.faqTitle;
	}

	public void setFaqTitle(String faqTitle) {
		this.faqTitle = faqTitle;
	}

	@Column(name = "faq_content")
	public String getFaqContent() {
		return this.faqContent;
	}

	public void setFaqContent(String faqContent) {
		this.faqContent = faqContent;
	}

	@Column(name = "enabled", length = 5)
	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
