package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FeedbackTemplate generated by hbm2java
 */
@Entity
@Table(name = "feedback_template", schema = "unipointmain")
public class FeedbackTemplate implements java.io.Serializable {

	private long feedbacktemplateid;
	private Merchant merchant;
	private MerchantUser merchantUserByAddedByRef;
	private MerchantUser merchantUserByLastModifiedByRef;
	private String title;
	private String description;
	private String createddatetime;
	private String feedbackjson;
	private String status;
	private String lastaccessed;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public FeedbackTemplate() {
	}

	public FeedbackTemplate(long feedbacktemplateid) {
		this.feedbacktemplateid = feedbacktemplateid;
	}

	public FeedbackTemplate(long feedbacktemplateid, Merchant merchant, MerchantUser merchantUserByAddedByRef,
			MerchantUser merchantUserByLastModifiedByRef, String title, String description, String createddatetime,
			String feedbackjson, String status, String lastaccessed, String addedDateTime, String lastModifiedDateTime,
			String lastModifiedFields) {
		this.feedbacktemplateid = feedbacktemplateid;
		this.merchant = merchant;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.title = title;
		this.description = description;
		this.createddatetime = createddatetime;
		this.feedbackjson = feedbackjson;
		this.status = status;
		this.lastaccessed = lastaccessed;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id

	@Column(name = "feedbacktemplateid", unique = true, nullable = false)
	public long getFeedbacktemplateid() {
		return this.feedbacktemplateid;
	}

	public void setFeedbacktemplateid(long feedbacktemplateid) {
		this.feedbacktemplateid = feedbacktemplateid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_ref_id")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "createddatetime", length = 100)
	public String getCreateddatetime() {
		return this.createddatetime;
	}

	public void setCreateddatetime(String createddatetime) {
		this.createddatetime = createddatetime;
	}

	@Column(name = "feedbackjson")
	public String getFeedbackjson() {
		return this.feedbackjson;
	}

	public void setFeedbackjson(String feedbackjson) {
		this.feedbackjson = feedbackjson;
	}

	@Column(name = "status", length = 5)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "lastaccessed", length = 100)
	public String getLastaccessed() {
		return this.lastaccessed;
	}

	public void setLastaccessed(String lastaccessed) {
		this.lastaccessed = lastaccessed;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
