package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LoyaltyScheme generated by hbm2java
 */
@Entity
@Table(name = "loyalty_scheme", schema = "unipointmain")
public class LoyaltyScheme implements java.io.Serializable {

	private long schemeId;
	private Merchant merchant;
	private MerchantUser merchantUserByLastModifiedByRef;
	private MerchantUser merchantUserByAddedByRef;
	private Double minimumPurchaseAmount;
	private Double maximumPurchaseAmount;
	private String schemeName;
	private String expiryDateTime;
	private Double pointPercentage;
	private String demotingTimePeriod;
	private String updateInterval;
	private String schemeDescription;
	private String loyaltyPolicy;
	private String imageUrl;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public LoyaltyScheme() {
	}

	public LoyaltyScheme(long schemeId) {
		this.schemeId = schemeId;
	}

	public LoyaltyScheme(long schemeId, Merchant merchant, MerchantUser merchantUserByLastModifiedByRef,
			MerchantUser merchantUserByAddedByRef, Double minimumPurchaseAmount, Double maximumPurchaseAmount,
			String schemeName, String expiryDateTime, Double pointPercentage, String demotingTimePeriod,
			String updateInterval, String schemeDescription, String loyaltyPolicy, String imageUrl,
			String addedDateTime, String lastModifiedDateTime, String lastModifiedFields) {
		this.schemeId = schemeId;
		this.merchant = merchant;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.minimumPurchaseAmount = minimumPurchaseAmount;
		this.maximumPurchaseAmount = maximumPurchaseAmount;
		this.schemeName = schemeName;
		this.expiryDateTime = expiryDateTime;
		this.pointPercentage = pointPercentage;
		this.demotingTimePeriod = demotingTimePeriod;
		this.updateInterval = updateInterval;
		this.schemeDescription = schemeDescription;
		this.loyaltyPolicy = loyaltyPolicy;
		this.imageUrl = imageUrl;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id
	@SequenceGenerator(name="pk_sequence",sequenceName="unipointmain.uni_loyalty_schema_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
	@Column(name = "scheme_id", unique = true, nullable = false)
	public long getSchemeId() {
		return this.schemeId;
	}

	public void setSchemeId(long schemeId) {
		this.schemeId = schemeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_id")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@Column(name = "minimum_purchase_amount", precision = 17, scale = 17)
	public Double getMinimumPurchaseAmount() {
		return this.minimumPurchaseAmount;
	}

	public void setMinimumPurchaseAmount(Double minimumPurchaseAmount) {
		this.minimumPurchaseAmount = minimumPurchaseAmount;
	}

	@Column(name = "maximum_purchase_amount", precision = 17, scale = 17)
	public Double getMaximumPurchaseAmount() {
		return this.maximumPurchaseAmount;
	}

	public void setMaximumPurchaseAmount(Double maximumPurchaseAmount) {
		this.maximumPurchaseAmount = maximumPurchaseAmount;
	}

	@Column(name = "scheme_name", length = 100)
	public String getSchemeName() {
		return this.schemeName;
	}

	public void setSchemeName(String schemeName) {
		this.schemeName = schemeName;
	}

	@Column(name = "expiry_date_time", length = 100)
	public String getExpiryDateTime() {
		return this.expiryDateTime;
	}

	public void setExpiryDateTime(String expiryDateTime) {
		this.expiryDateTime = expiryDateTime;
	}

	@Column(name = "point_percentage", precision = 17, scale = 17)
	public Double getPointPercentage() {
		return this.pointPercentage;
	}

	public void setPointPercentage(Double pointPercentage) {
		this.pointPercentage = pointPercentage;
	}

	@Column(name = "demoting_time_period", length = 100)
	public String getDemotingTimePeriod() {
		return this.demotingTimePeriod;
	}

	public void setDemotingTimePeriod(String demotingTimePeriod) {
		this.demotingTimePeriod = demotingTimePeriod;
	}

	@Column(name = "update_interval", length = 100)
	public String getUpdateInterval() {
		return this.updateInterval;
	}

	public void setUpdateInterval(String updateInterval) {
		this.updateInterval = updateInterval;
	}

	@Column(name = "scheme_description")
	public String getSchemeDescription() {
		return this.schemeDescription;
	}

	public void setSchemeDescription(String schemeDescription) {
		this.schemeDescription = schemeDescription;
	}

	@Column(name = "loyalty_policy")
	public String getLoyaltyPolicy() {
		return this.loyaltyPolicy;
	}

	public void setLoyaltyPolicy(String loyaltyPolicy) {
		this.loyaltyPolicy = loyaltyPolicy;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
