package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MerchantFeedback generated by hbm2java
 */
@Entity
@Table(name = "merchant_feedback", schema = "unipointmain")
public class MerchantFeedback implements java.io.Serializable {

	private long feedbackid;
	private Merchant merchant;
	private MerchantUser merchantUser;
	private String createddatetime;
	private String feedbacktitle;
	private String description;
	private String enabled;
	private Long pointsallocated;
	private String lastmodified;
	private String feedbackjson;
	private Set<SubmittedFeedback> submittedFeedbacks = new HashSet<SubmittedFeedback>(0);

	public MerchantFeedback() {
	}

	public MerchantFeedback(long feedbackid) {
		this.feedbackid = feedbackid;
	}

	public MerchantFeedback(long feedbackid, Merchant merchant, MerchantUser merchantUser, String createddatetime,
			String feedbacktitle, String description, String enabled, Long pointsallocated, String lastmodified,
			String feedbackjson, Set<SubmittedFeedback> submittedFeedbacks) {
		this.feedbackid = feedbackid;
		this.merchant = merchant;
		this.merchantUser = merchantUser;
		this.createddatetime = createddatetime;
		this.feedbacktitle = feedbacktitle;
		this.description = description;
		this.enabled = enabled;
		this.pointsallocated = pointsallocated;
		this.lastmodified = lastmodified;
		this.feedbackjson = feedbackjson;
		this.submittedFeedbacks = submittedFeedbacks;
	}

	@Id

	@Column(name = "feedbackid", unique = true, nullable = false)
	public long getFeedbackid() {
		return this.feedbackid;
	}

	public void setFeedbackid(long feedbackid) {
		this.feedbackid = feedbackid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_ref_id")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdby_merchant_user_ref_id")
	public MerchantUser getMerchantUser() {
		return this.merchantUser;
	}

	public void setMerchantUser(MerchantUser merchantUser) {
		this.merchantUser = merchantUser;
	}

	@Column(name = "createddatetime", length = 100)
	public String getCreateddatetime() {
		return this.createddatetime;
	}

	public void setCreateddatetime(String createddatetime) {
		this.createddatetime = createddatetime;
	}

	@Column(name = "feedbacktitle")
	public String getFeedbacktitle() {
		return this.feedbacktitle;
	}

	public void setFeedbacktitle(String feedbacktitle) {
		this.feedbacktitle = feedbacktitle;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "enabled", length = 5)
	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	@Column(name = "pointsallocated")
	public Long getPointsallocated() {
		return this.pointsallocated;
	}

	public void setPointsallocated(Long pointsallocated) {
		this.pointsallocated = pointsallocated;
	}

	@Column(name = "lastmodified", length = 100)
	public String getLastmodified() {
		return this.lastmodified;
	}

	public void setLastmodified(String lastmodified) {
		this.lastmodified = lastmodified;
	}

	@Column(name = "feedbackjson")
	public String getFeedbackjson() {
		return this.feedbackjson;
	}

	public void setFeedbackjson(String feedbackjson) {
		this.feedbackjson = feedbackjson;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchantFeedback")
	public Set<SubmittedFeedback> getSubmittedFeedbacks() {
		return this.submittedFeedbacks;
	}

	public void setSubmittedFeedbacks(Set<SubmittedFeedback> submittedFeedbacks) {
		this.submittedFeedbacks = submittedFeedbacks;
	}

}
