package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MerchantCustomer generated by hbm2java
 */
@Entity
@Table(name = "merchant_customer", schema = "unipointmain")
public class MerchantCustomer implements java.io.Serializable {

	private MerchantCustomerId id;
	private Merchant merchant;
	private MerchantUser merchantUserByAddedByRef;
	private MerchantUser merchantUserByLastModifiedByRef;
	private UnipointCustomerProfile unipointCustomerProfile;
	private String cardNumber;
	private String accountNumber;
	private String registrationDatetime;
	private String contactNumber;
	private BigDecimal mobilePhonenum;
	private String customerFirstname;
	private String customerLastname;
	private String gender;
	private String postalAddress;
	private String emailAddress;
	private Long schemeRefId;
	private String location;
	private BigDecimal points;
	private BigDecimal redeemedPoints;
	private BigDecimal totalPoints;
	private String enabled;
	private String merchantCustomerId;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public MerchantCustomer() {
	}

	public MerchantCustomer(MerchantCustomerId id, Merchant merchant, UnipointCustomerProfile unipointCustomerProfile,
			String enabled, String merchantCustomerId) {
		this.id = id;
		this.merchant = merchant;
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.enabled = enabled;
		this.merchantCustomerId = merchantCustomerId;
	}

	public MerchantCustomer(MerchantCustomerId id, Merchant merchant, MerchantUser merchantUserByAddedByRef,
			MerchantUser merchantUserByLastModifiedByRef, UnipointCustomerProfile unipointCustomerProfile,
			String cardNumber, String accountNumber, String registrationDatetime, String contactNumber,
			BigDecimal mobilePhonenum, String customerFirstname, String customerLastname, String gender,
			String postalAddress, String emailAddress, Long schemeRefId, String location, BigDecimal points,
			BigDecimal redeemedPoints, BigDecimal totalPoints, String enabled, String merchantCustomerId,
			String addedDateTime, String lastModifiedDateTime, String lastModifiedFields) {
		this.id = id;
		this.merchant = merchant;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.cardNumber = cardNumber;
		this.accountNumber = accountNumber;
		this.registrationDatetime = registrationDatetime;
		this.contactNumber = contactNumber;
		this.mobilePhonenum = mobilePhonenum;
		this.customerFirstname = customerFirstname;
		this.customerLastname = customerLastname;
		this.gender = gender;
		this.postalAddress = postalAddress;
		this.emailAddress = emailAddress;
		this.schemeRefId = schemeRefId;
		this.location = location;
		this.points = points;
		this.redeemedPoints = redeemedPoints;
		this.totalPoints = totalPoints;
		this.enabled = enabled;
		this.merchantCustomerId = merchantCustomerId;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unipointCustomerRefId", column = @Column(name = "unipoint_customer_ref_id", nullable = false)),
			@AttributeOverride(name = "merchantRefId", column = @Column(name = "merchant_ref_id", nullable = false)) })
	public MerchantCustomerId getId() {
		return this.id;
	}

	public void setId(MerchantCustomerId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_ref_id", nullable = false, insertable = false, updatable = false)
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unipoint_customer_ref_id", nullable = false, insertable = false, updatable = false)
	public UnipointCustomerProfile getUnipointCustomerProfile() {
		return this.unipointCustomerProfile;
	}

	public void setUnipointCustomerProfile(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	@Column(name = "card_number")
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "account_number", length = 50)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "registration_datetime", length = 100)
	public String getRegistrationDatetime() {
		return this.registrationDatetime;
	}

	public void setRegistrationDatetime(String registrationDatetime) {
		this.registrationDatetime = registrationDatetime;
	}

	@Column(name = "contact_number")
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "mobile_phonenum", precision = 131089, scale = 0)
	public BigDecimal getMobilePhonenum() {
		return this.mobilePhonenum;
	}

	public void setMobilePhonenum(BigDecimal mobilePhonenum) {
		this.mobilePhonenum = mobilePhonenum;
	}

	@Column(name = "customer_firstname")
	public String getCustomerFirstname() {
		return this.customerFirstname;
	}

	public void setCustomerFirstname(String customerFirstname) {
		this.customerFirstname = customerFirstname;
	}

	@Column(name = "customer_lastname")
	public String getCustomerLastname() {
		return this.customerLastname;
	}

	public void setCustomerLastname(String customerLastname) {
		this.customerLastname = customerLastname;
	}

	@Column(name = "gender")
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "postal_address")
	public String getPostalAddress() {
		return this.postalAddress;
	}

	public void setPostalAddress(String postalAddress) {
		this.postalAddress = postalAddress;
	}

	@Column(name = "email_address")
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "scheme_ref_id")
	public Long getSchemeRefId() {
		return this.schemeRefId;
	}

	public void setSchemeRefId(Long schemeRefId) {
		this.schemeRefId = schemeRefId;
	}

	@Column(name = "location", length = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "points", precision = 131089, scale = 0)
	public BigDecimal getPoints() {
		return this.points;
	}

	public void setPoints(BigDecimal points) {
		this.points = points;
	}

	@Column(name = "redeemed_points", precision = 131089, scale = 0)
	public BigDecimal getRedeemedPoints() {
		return this.redeemedPoints;
	}

	public void setRedeemedPoints(BigDecimal redeemedPoints) {
		this.redeemedPoints = redeemedPoints;
	}

	@Column(name = "total_points", precision = 131089, scale = 0)
	public BigDecimal getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(BigDecimal totalPoints) {
		this.totalPoints = totalPoints;
	}

	@Column(name = "enabled", nullable = false, length = 5)
	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	@Column(name = "merchant_customer_id", nullable = false)
	public String getMerchantCustomerId() {
		return this.merchantCustomerId;
	}

	public void setMerchantCustomerId(String merchantCustomerId) {
		this.merchantCustomerId = merchantCustomerId;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
