package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MerchantCustomerId generated by hbm2java
 */
@Embeddable
public class MerchantCustomerId implements java.io.Serializable {

	private long unipointCustomerRefId;
	private long merchantRefId;

	public MerchantCustomerId() {
	}

	public MerchantCustomerId(long unipointCustomerRefId, long merchantRefId) {
		this.unipointCustomerRefId = unipointCustomerRefId;
		this.merchantRefId = merchantRefId;
	}

	@Column(name = "unipoint_customer_ref_id", nullable = false)
	public long getUnipointCustomerRefId() {
		return this.unipointCustomerRefId;
	}

	public void setUnipointCustomerRefId(long unipointCustomerRefId) {
		this.unipointCustomerRefId = unipointCustomerRefId;
	}

	@Column(name = "merchant_ref_id", nullable = false)
	public long getMerchantRefId() {
		return this.merchantRefId;
	}

	public void setMerchantRefId(long merchantRefId) {
		this.merchantRefId = merchantRefId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MerchantCustomerId))
			return false;
		MerchantCustomerId castOther = (MerchantCustomerId) other;

		return (this.getUnipointCustomerRefId() == castOther.getUnipointCustomerRefId())
				&& (this.getMerchantRefId() == castOther.getMerchantRefId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUnipointCustomerRefId();
		result = 37 * result + (int) this.getMerchantRefId();
		return result;
	}

}
