package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MerchantProfile generated by hbm2java
 */
@Entity
@Table(name = "merchant_profile", schema = "unipointmain")
public class MerchantProfile implements java.io.Serializable {

	private long merchantProfileId;
	private Merchant merchant;
	private MerchantUser merchantUserByAddedByRef;
	private MerchantUser merchantUserByLastModifiedByRef;
	private String organizationName;
	private String description;
	private String website;
	private String emailAddress;
	private BigDecimal phonenumber;
	private String joinedDate;
	private String shortAddress;
	private String shortcode;
	private String address;
	private String latlong;
	private BigDecimal faxNumber;
	private String logo64;
	private String logo256;
	private String logo512;
	private String coverUrl;
	private String country;
	private String categoryName;
	private String logo128;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public MerchantProfile() {
	}

	public MerchantProfile(long merchantProfileId) {
		this.merchantProfileId = merchantProfileId;
	}

	public MerchantProfile(long merchantProfileId, Merchant merchant, MerchantUser merchantUserByAddedByRef,
			MerchantUser merchantUserByLastModifiedByRef, String organizationName, String description, String website,
			String emailAddress, BigDecimal phonenumber, String joinedDate, String shortAddress, String shortcode,
			String address, String latlong, BigDecimal faxNumber, String logo64, String logo256, String logo512,
			String coverUrl, String country, String categoryName, String logo128, String addedDateTime,
			String lastModifiedDateTime, String lastModifiedFields) {
		this.merchantProfileId = merchantProfileId;
		this.merchant = merchant;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.organizationName = organizationName;
		this.description = description;
		this.website = website;
		this.emailAddress = emailAddress;
		this.phonenumber = phonenumber;
		this.joinedDate = joinedDate;
		this.shortAddress = shortAddress;
		this.shortcode = shortcode;
		this.address = address;
		this.latlong = latlong;
		this.faxNumber = faxNumber;
		this.logo64 = logo64;
		this.logo256 = logo256;
		this.logo512 = logo512;
		this.coverUrl = coverUrl;
		this.country = country;
		this.categoryName = categoryName;
		this.logo128 = logo128;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id

	@Column(name = "merchant_profile_id", unique = true, nullable = false)
	public long getMerchantProfileId() {
		return this.merchantProfileId;
	}

	public void setMerchantProfileId(long merchantProfileId) {
		this.merchantProfileId = merchantProfileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_ref_id")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@Column(name = "organization_name")
	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "website", length = 100)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "email_address", length = 100)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "phonenumber", precision = 131089, scale = 0)
	public BigDecimal getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(BigDecimal phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "joined_date", length = 100)
	public String getJoinedDate() {
		return this.joinedDate;
	}

	public void setJoinedDate(String joinedDate) {
		this.joinedDate = joinedDate;
	}

	@Column(name = "short_address")
	public String getShortAddress() {
		return this.shortAddress;
	}

	public void setShortAddress(String shortAddress) {
		this.shortAddress = shortAddress;
	}

	@Column(name = "shortcode")
	public String getShortcode() {
		return this.shortcode;
	}

	public void setShortcode(String shortcode) {
		this.shortcode = shortcode;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "latlong", length = 100)
	public String getLatlong() {
		return this.latlong;
	}

	public void setLatlong(String latlong) {
		this.latlong = latlong;
	}

	@Column(name = "fax_number", precision = 131089, scale = 0)
	public BigDecimal getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(BigDecimal faxNumber) {
		this.faxNumber = faxNumber;
	}

	@Column(name = "logo64")
	public String getLogo64() {
		return this.logo64;
	}

	public void setLogo64(String logo64) {
		this.logo64 = logo64;
	}

	@Column(name = "logo256")
	public String getLogo256() {
		return this.logo256;
	}

	public void setLogo256(String logo256) {
		this.logo256 = logo256;
	}

	@Column(name = "logo512")
	public String getLogo512() {
		return this.logo512;
	}

	public void setLogo512(String logo512) {
		this.logo512 = logo512;
	}

	@Column(name = "cover_url")
	public String getCoverUrl() {
		return this.coverUrl;
	}

	public void setCoverUrl(String coverUrl) {
		this.coverUrl = coverUrl;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "category_name")
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "logo128")
	public String getLogo128() {
		return this.logo128;
	}

	public void setLogo128(String logo128) {
		this.logo128 = logo128;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
