package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Merchant generated by hbm2java
 */
@Entity
@Table(name = "merchant", schema = "unipointmain")
public class Merchant implements java.io.Serializable {

	private long merchantId;
	private MerchantUser merchantUserByAddedByRef;
	private MerchantUser merchantUserByLastModifiedByRef;
	private Organization organization;
	private String merchantName;
	private String description;
	private String website;
	private String emailAddress;
	private BigDecimal phonenumber;
	private String joinedDatetime;
	private String shortAddress;
	private String shortcode;
	private String address;
	private String latlong;
	private BigDecimal faxnUmber;
	private String logo64;
	private String logo128;
	private String logo256;
	private String logo512;
	private String merchantCoverUrl;
	private String merchantCategoryRefId;
	private String country;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;
	private Set<CardLog> cardLogs = new HashSet<CardLog>(0);
	private Set<Catagory> catagories = new HashSet<Catagory>(0);
	private Set<Outlet> outlets = new HashSet<Outlet>(0);
	private Set<CustomerRequests> customerRequestses = new HashSet<CustomerRequests>(0);
	private Set<MerchantUser> merchantUsers = new HashSet<MerchantUser>(0);
	private Set<MerchantCustomer> merchantCustomers = new HashSet<MerchantCustomer>(0);
	private Set<DisabledCustomer> disabledCustomers = new HashSet<DisabledCustomer>(0);
	private Set<MerchantProfile> merchantProfiles = new HashSet<MerchantProfile>(0);
	private Set<FeedbackTemplate> feedbackTemplates = new HashSet<FeedbackTemplate>(0);
	private Set<SubscribeMerchant> subscribeMerchants = new HashSet<SubscribeMerchant>(0);
	private Set<LoyaltyScheme> loyaltySchemes = new HashSet<LoyaltyScheme>(0);
	private Set<PointConversion> pointConversions = new HashSet<PointConversion>(0);
	private Set<PointRewardType> pointRewardTypes = new HashSet<PointRewardType>(0);
	private Set<MerchantFeedback> merchantFeedbacks = new HashSet<MerchantFeedback>(0);
	private Set<PointRewards> pointRewardses = new HashSet<PointRewards>(0);
	private Set<BuyPoint> buyPoints = new HashSet<BuyPoint>(0);
	private Set<Faq> faqs = new HashSet<Faq>(0);
	private Set<Offer> offers = new HashSet<Offer>(0);

	public Merchant() {
	}

	public Merchant(long merchantId) {
		this.merchantId = merchantId;
	}

	public Merchant(long merchantId, MerchantUser merchantUserByAddedByRef,
			MerchantUser merchantUserByLastModifiedByRef, Organization organization, String merchantName,
			String description, String website, String emailAddress, BigDecimal phonenumber, String joinedDatetime,
			String shortAddress, String shortcode, String address, String latlong, BigDecimal faxnUmber, String logo64,
			String logo128, String logo256, String logo512, String merchantCoverUrl, String merchantCategoryRefId,
			String country, String addedDateTime, String lastModifiedDateTime, String lastModifiedFields,
			Set<CardLog> cardLogs, Set<Catagory> catagories, Set<Outlet> outlets,
			Set<CustomerRequests> customerRequestses, Set<MerchantUser> merchantUsers,
			Set<MerchantCustomer> merchantCustomers, Set<DisabledCustomer> disabledCustomers,
			Set<MerchantProfile> merchantProfiles, Set<FeedbackTemplate> feedbackTemplates,
			Set<SubscribeMerchant> subscribeMerchants, Set<LoyaltyScheme> loyaltySchemes,
			Set<PointConversion> pointConversions, Set<PointRewardType> pointRewardTypes,
			Set<MerchantFeedback> merchantFeedbacks, Set<PointRewards> pointRewardses, Set<BuyPoint> buyPoints,
			Set<Faq> faqs, Set<Offer> offers) {
		this.merchantId = merchantId;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.organization = organization;
		this.merchantName = merchantName;
		this.description = description;
		this.website = website;
		this.emailAddress = emailAddress;
		this.phonenumber = phonenumber;
		this.joinedDatetime = joinedDatetime;
		this.shortAddress = shortAddress;
		this.shortcode = shortcode;
		this.address = address;
		this.latlong = latlong;
		this.faxnUmber = faxnUmber;
		this.logo64 = logo64;
		this.logo128 = logo128;
		this.logo256 = logo256;
		this.logo512 = logo512;
		this.merchantCoverUrl = merchantCoverUrl;
		this.merchantCategoryRefId = merchantCategoryRefId;
		this.country = country;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
		this.cardLogs = cardLogs;
		this.catagories = catagories;
		this.outlets = outlets;
		this.customerRequestses = customerRequestses;
		this.merchantUsers = merchantUsers;
		this.merchantCustomers = merchantCustomers;
		this.disabledCustomers = disabledCustomers;
		this.merchantProfiles = merchantProfiles;
		this.feedbackTemplates = feedbackTemplates;
		this.subscribeMerchants = subscribeMerchants;
		this.loyaltySchemes = loyaltySchemes;
		this.pointConversions = pointConversions;
		this.pointRewardTypes = pointRewardTypes;
		this.merchantFeedbacks = merchantFeedbacks;
		this.pointRewardses = pointRewardses;
		this.buyPoints = buyPoints;
		this.faqs = faqs;
		this.offers = offers;
	}

	@Id
	@SequenceGenerator(name="pk_sequence",sequenceName="unipointmain.mer_user_pk_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
	@Column(name = "merchant_id", unique = true, nullable = false)
	public long getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(long merchantId) {
		this.merchantId = merchantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization_ref_id")
	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	@Column(name = "merchant_name")
	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "website", length = 200)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "email_address", length = 100)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "phonenumber", precision = 131089, scale = 0)
	public BigDecimal getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(BigDecimal phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "joined_datetime", length = 100)
	public String getJoinedDatetime() {
		return this.joinedDatetime;
	}

	public void setJoinedDatetime(String joinedDatetime) {
		this.joinedDatetime = joinedDatetime;
	}

	@Column(name = "short_address")
	public String getShortAddress() {
		return this.shortAddress;
	}

	public void setShortAddress(String shortAddress) {
		this.shortAddress = shortAddress;
	}

	@Column(name = "shortcode")
	public String getShortcode() {
		return this.shortcode;
	}

	public void setShortcode(String shortcode) {
		this.shortcode = shortcode;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "latlong", length = 100)
	public String getLatlong() {
		return this.latlong;
	}

	public void setLatlong(String latlong) {
		this.latlong = latlong;
	}

	@Column(name = "faxn_umber", precision = 131089, scale = 0)
	public BigDecimal getFaxnUmber() {
		return this.faxnUmber;
	}

	public void setFaxnUmber(BigDecimal faxnUmber) {
		this.faxnUmber = faxnUmber;
	}

	@Column(name = "logo64")
	public String getLogo64() {
		return this.logo64;
	}

	public void setLogo64(String logo64) {
		this.logo64 = logo64;
	}

	@Column(name = "logo128")
	public String getLogo128() {
		return this.logo128;
	}

	public void setLogo128(String logo128) {
		this.logo128 = logo128;
	}

	@Column(name = "logo256")
	public String getLogo256() {
		return this.logo256;
	}

	public void setLogo256(String logo256) {
		this.logo256 = logo256;
	}

	@Column(name = "logo512")
	public String getLogo512() {
		return this.logo512;
	}

	public void setLogo512(String logo512) {
		this.logo512 = logo512;
	}

	@Column(name = "merchant_cover_url")
	public String getMerchantCoverUrl() {
		return this.merchantCoverUrl;
	}

	public void setMerchantCoverUrl(String merchantCoverUrl) {
		this.merchantCoverUrl = merchantCoverUrl;
	}

	@Column(name = "merchant_category_ref_id")
	public String getMerchantCategoryRefId() {
		return this.merchantCategoryRefId;
	}

	public void setMerchantCategoryRefId(String merchantCategoryRefId) {
		this.merchantCategoryRefId = merchantCategoryRefId;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<CardLog> getCardLogs() {
		return this.cardLogs;
	}

	public void setCardLogs(Set<CardLog> cardLogs) {
		this.cardLogs = cardLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Catagory> getCatagories() {
		return this.catagories;
	}

	public void setCatagories(Set<Catagory> catagories) {
		this.catagories = catagories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Outlet> getOutlets() {
		return this.outlets;
	}

	public void setOutlets(Set<Outlet> outlets) {
		this.outlets = outlets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<CustomerRequests> getCustomerRequestses() {
		return this.customerRequestses;
	}

	public void setCustomerRequestses(Set<CustomerRequests> customerRequestses) {
		this.customerRequestses = customerRequestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<MerchantUser> getMerchantUsers() {
		return this.merchantUsers;
	}

	public void setMerchantUsers(Set<MerchantUser> merchantUsers) {
		this.merchantUsers = merchantUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<MerchantCustomer> getMerchantCustomers() {
		return this.merchantCustomers;
	}

	public void setMerchantCustomers(Set<MerchantCustomer> merchantCustomers) {
		this.merchantCustomers = merchantCustomers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<DisabledCustomer> getDisabledCustomers() {
		return this.disabledCustomers;
	}

	public void setDisabledCustomers(Set<DisabledCustomer> disabledCustomers) {
		this.disabledCustomers = disabledCustomers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<MerchantProfile> getMerchantProfiles() {
		return this.merchantProfiles;
	}

	public void setMerchantProfiles(Set<MerchantProfile> merchantProfiles) {
		this.merchantProfiles = merchantProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<FeedbackTemplate> getFeedbackTemplates() {
		return this.feedbackTemplates;
	}

	public void setFeedbackTemplates(Set<FeedbackTemplate> feedbackTemplates) {
		this.feedbackTemplates = feedbackTemplates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<SubscribeMerchant> getSubscribeMerchants() {
		return this.subscribeMerchants;
	}

	public void setSubscribeMerchants(Set<SubscribeMerchant> subscribeMerchants) {
		this.subscribeMerchants = subscribeMerchants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<LoyaltyScheme> getLoyaltySchemes() {
		return this.loyaltySchemes;
	}

	public void setLoyaltySchemes(Set<LoyaltyScheme> loyaltySchemes) {
		this.loyaltySchemes = loyaltySchemes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<PointConversion> getPointConversions() {
		return this.pointConversions;
	}

	public void setPointConversions(Set<PointConversion> pointConversions) {
		this.pointConversions = pointConversions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<PointRewardType> getPointRewardTypes() {
		return this.pointRewardTypes;
	}

	public void setPointRewardTypes(Set<PointRewardType> pointRewardTypes) {
		this.pointRewardTypes = pointRewardTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<MerchantFeedback> getMerchantFeedbacks() {
		return this.merchantFeedbacks;
	}

	public void setMerchantFeedbacks(Set<MerchantFeedback> merchantFeedbacks) {
		this.merchantFeedbacks = merchantFeedbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<PointRewards> getPointRewardses() {
		return this.pointRewardses;
	}

	public void setPointRewardses(Set<PointRewards> pointRewardses) {
		this.pointRewardses = pointRewardses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<BuyPoint> getBuyPoints() {
		return this.buyPoints;
	}

	public void setBuyPoints(Set<BuyPoint> buyPoints) {
		this.buyPoints = buyPoints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Faq> getFaqs() {
		return this.faqs;
	}

	public void setFaqs(Set<Faq> faqs) {
		this.faqs = faqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Offer> getOffers() {
		return this.offers;
	}

	public void setOffers(Set<Offer> offers) {
		this.offers = offers;
	}

}
