package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Offer generated by hbm2java
 */
@Entity
@Table(name = "offer", schema = "unipointmain")
public class Offer implements java.io.Serializable {

	private long offerid;
	private Merchant merchant;
	private MerchantUser merchantUserByAddedByRef;
	private MerchantUser merchantUserByLastModifiedByRef;
	private String issueDateTime;
	private BigDecimal pointsAllocated;
	private String expiryDate;
	private String offerHeading;
	private String offerSubheading;
	private String offerDescription;
	private String offerFilterTypes;
	private String videoUrl;
	private String offerType;
	private String offerContent;
	private String offerRedemtionCode;
	private String merchantLogoUrl;
	private String offerPromoCode;
	private BigDecimal offerDiscount;
	private BigDecimal offerPrice;
	private String offerAvailableBranches;
	private String enabled;
	private String imageUrl2;
	private String imageUrl3;
	private String imageUrl4;
	private String imageUrl5;
	private Short offerClaimLimit;
	private String imageUrl1;
	private Long availableUnits;
	private Long reservedUnits;
	private String category;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;
	private Set<RecoImage> recoImages = new HashSet<RecoImage>(0);
	private Set<OfferReservation> offerReservations = new HashSet<OfferReservation>(0);
	private Set<OfferLeaflet> offerLeaflets = new HashSet<OfferLeaflet>(0);
	private Set<BuzzedMe> buzzedMes = new HashSet<BuzzedMe>(0);
	private Set<OfferClaim> offerClaims = new HashSet<OfferClaim>(0);
	private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);

	public Offer() {
	}

	public Offer(long offerid) {
		this.offerid = offerid;
	}

	public Offer(long offerid, Merchant merchant, MerchantUser merchantUserByAddedByRef,
			MerchantUser merchantUserByLastModifiedByRef, String issueDateTime, BigDecimal pointsAllocated,
			String expiryDate, String offerHeading, String offerSubheading, String offerDescription,
			String offerFilterTypes, String videoUrl, String offerType, String offerContent, String offerRedemtionCode,
			String merchantLogoUrl, String offerPromoCode, BigDecimal offerDiscount, BigDecimal offerPrice,
			String offerAvailableBranches, String enabled, String imageUrl2, String imageUrl3, String imageUrl4,
			String imageUrl5, Short offerClaimLimit, String imageUrl1, Long availableUnits, Long reservedUnits,
			String category, String addedDateTime, String lastModifiedDateTime, String lastModifiedFields,
			Set<RecoImage> recoImages, Set<OfferReservation> offerReservations, Set<OfferLeaflet> offerLeaflets,
			Set<BuzzedMe> buzzedMes, Set<OfferClaim> offerClaims, Set<Wishlist> wishlists) {
		this.offerid = offerid;
		this.merchant = merchant;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.issueDateTime = issueDateTime;
		this.pointsAllocated = pointsAllocated;
		this.expiryDate = expiryDate;
		this.offerHeading = offerHeading;
		this.offerSubheading = offerSubheading;
		this.offerDescription = offerDescription;
		this.offerFilterTypes = offerFilterTypes;
		this.videoUrl = videoUrl;
		this.offerType = offerType;
		this.offerContent = offerContent;
		this.offerRedemtionCode = offerRedemtionCode;
		this.merchantLogoUrl = merchantLogoUrl;
		this.offerPromoCode = offerPromoCode;
		this.offerDiscount = offerDiscount;
		this.offerPrice = offerPrice;
		this.offerAvailableBranches = offerAvailableBranches;
		this.enabled = enabled;
		this.imageUrl2 = imageUrl2;
		this.imageUrl3 = imageUrl3;
		this.imageUrl4 = imageUrl4;
		this.imageUrl5 = imageUrl5;
		this.offerClaimLimit = offerClaimLimit;
		this.imageUrl1 = imageUrl1;
		this.availableUnits = availableUnits;
		this.reservedUnits = reservedUnits;
		this.category = category;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
		this.recoImages = recoImages;
		this.offerReservations = offerReservations;
		this.offerLeaflets = offerLeaflets;
		this.buzzedMes = buzzedMes;
		this.offerClaims = offerClaims;
		this.wishlists = wishlists;
	}

	@Id
	@SequenceGenerator(name="pk_sequence",sequenceName="unipointmain.mech_cus_offer_pk_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
	@Column(name = "offerid", unique = true, nullable = false)
	public long getOfferid() {
		return this.offerid;
	}

	public void setOfferid(long offerid) {
		this.offerid = offerid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_ref_id")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@Column(name = "issue_date_time", length = 100)
	public String getIssueDateTime() {
		return this.issueDateTime;
	}

	public void setIssueDateTime(String issueDateTime) {
		this.issueDateTime = issueDateTime;
	}

	@Column(name = "points_allocated", precision = 131089, scale = 0)
	public BigDecimal getPointsAllocated() {
		return this.pointsAllocated;
	}

	public void setPointsAllocated(BigDecimal pointsAllocated) {
		this.pointsAllocated = pointsAllocated;
	}

	@Column(name = "expiry_date", length = 100)
	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "offer_heading")
	public String getOfferHeading() {
		return this.offerHeading;
	}

	public void setOfferHeading(String offerHeading) {
		this.offerHeading = offerHeading;
	}

	@Column(name = "offer_subheading")
	public String getOfferSubheading() {
		return this.offerSubheading;
	}

	public void setOfferSubheading(String offerSubheading) {
		this.offerSubheading = offerSubheading;
	}

	@Column(name = "offer_description", length = 2000)
	public String getOfferDescription() {
		return this.offerDescription;
	}

	public void setOfferDescription(String offerDescription) {
		this.offerDescription = offerDescription;
	}

	@Column(name = "offer_filter_types")
	public String getOfferFilterTypes() {
		return this.offerFilterTypes;
	}

	public void setOfferFilterTypes(String offerFilterTypes) {
		this.offerFilterTypes = offerFilterTypes;
	}

	@Column(name = "video_url", length = 300)
	public String getVideoUrl() {
		return this.videoUrl;
	}

	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}

	@Column(name = "offer_type", length = 50)
	public String getOfferType() {
		return this.offerType;
	}

	public void setOfferType(String offerType) {
		this.offerType = offerType;
	}

	@Column(name = "offer_content")
	public String getOfferContent() {
		return this.offerContent;
	}

	public void setOfferContent(String offerContent) {
		this.offerContent = offerContent;
	}

	@Column(name = "offer_redemtion_code")
	public String getOfferRedemtionCode() {
		return this.offerRedemtionCode;
	}

	public void setOfferRedemtionCode(String offerRedemtionCode) {
		this.offerRedemtionCode = offerRedemtionCode;
	}

	@Column(name = "merchant_logo_url")
	public String getMerchantLogoUrl() {
		return this.merchantLogoUrl;
	}

	public void setMerchantLogoUrl(String merchantLogoUrl) {
		this.merchantLogoUrl = merchantLogoUrl;
	}

	@Column(name = "offer_promo_code", length = 20)
	public String getOfferPromoCode() {
		return this.offerPromoCode;
	}

	public void setOfferPromoCode(String offerPromoCode) {
		this.offerPromoCode = offerPromoCode;
	}

	@Column(name = "offer_discount", precision = 131089, scale = 0)
	public BigDecimal getOfferDiscount() {
		return this.offerDiscount;
	}

	public void setOfferDiscount(BigDecimal offerDiscount) {
		this.offerDiscount = offerDiscount;
	}

	@Column(name = "offer_price", precision = 131089, scale = 0)
	public BigDecimal getOfferPrice() {
		return this.offerPrice;
	}

	public void setOfferPrice(BigDecimal offerPrice) {
		this.offerPrice = offerPrice;
	}

	@Column(name = "offer_available_branches")
	public String getOfferAvailableBranches() {
		return this.offerAvailableBranches;
	}

	public void setOfferAvailableBranches(String offerAvailableBranches) {
		this.offerAvailableBranches = offerAvailableBranches;
	}

	@Column(name = "enabled", length = 5)
	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	@Column(name = "image_url2", length = 300)
	public String getImageUrl2() {
		return this.imageUrl2;
	}

	public void setImageUrl2(String imageUrl2) {
		this.imageUrl2 = imageUrl2;
	}

	@Column(name = "image_url3", length = 300)
	public String getImageUrl3() {
		return this.imageUrl3;
	}

	public void setImageUrl3(String imageUrl3) {
		this.imageUrl3 = imageUrl3;
	}

	@Column(name = "image_url4", length = 300)
	public String getImageUrl4() {
		return this.imageUrl4;
	}

	public void setImageUrl4(String imageUrl4) {
		this.imageUrl4 = imageUrl4;
	}

	@Column(name = "image_url5", length = 300)
	public String getImageUrl5() {
		return this.imageUrl5;
	}

	public void setImageUrl5(String imageUrl5) {
		this.imageUrl5 = imageUrl5;
	}

	@Column(name = "offer_claim_limit")
	public Short getOfferClaimLimit() {
		return this.offerClaimLimit;
	}

	public void setOfferClaimLimit(Short offerClaimLimit) {
		this.offerClaimLimit = offerClaimLimit;
	}

	@Column(name = "image_url1", length = 300)
	public String getImageUrl1() {
		return this.imageUrl1;
	}

	public void setImageUrl1(String imageUrl1) {
		this.imageUrl1 = imageUrl1;
	}

	@Column(name = "available_units")
	public Long getAvailableUnits() {
		return this.availableUnits;
	}

	public void setAvailableUnits(Long availableUnits) {
		this.availableUnits = availableUnits;
	}

	@Column(name = "reserved_units")
	public Long getReservedUnits() {
		return this.reservedUnits;
	}

	public void setReservedUnits(Long reservedUnits) {
		this.reservedUnits = reservedUnits;
	}

	@Column(name = "category")
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offer")
	public Set<RecoImage> getRecoImages() {
		return this.recoImages;
	}

	public void setRecoImages(Set<RecoImage> recoImages) {
		this.recoImages = recoImages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offer")
	public Set<OfferReservation> getOfferReservations() {
		return this.offerReservations;
	}

	public void setOfferReservations(Set<OfferReservation> offerReservations) {
		this.offerReservations = offerReservations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offer")
	public Set<OfferLeaflet> getOfferLeaflets() {
		return this.offerLeaflets;
	}

	public void setOfferLeaflets(Set<OfferLeaflet> offerLeaflets) {
		this.offerLeaflets = offerLeaflets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offer")
	public Set<BuzzedMe> getBuzzedMes() {
		return this.buzzedMes;
	}

	public void setBuzzedMes(Set<BuzzedMe> buzzedMes) {
		this.buzzedMes = buzzedMes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offer")
	public Set<OfferClaim> getOfferClaims() {
		return this.offerClaims;
	}

	public void setOfferClaims(Set<OfferClaim> offerClaims) {
		this.offerClaims = offerClaims;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offer")
	public Set<Wishlist> getWishlists() {
		return this.wishlists;
	}

	public void setWishlists(Set<Wishlist> wishlists) {
		this.wishlists = wishlists;
	}

}
