package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OfferClaim generated by hbm2java
 */
@Entity
@Table(name = "offer_claim", schema = "unipointmain")
public class OfferClaim implements java.io.Serializable {

	private long offerClaimId;
	private MerchantUser merchantUserByLastModifiedByRef;
	private MerchantUser merchantUserByAddedByRef;
	private Offer offer;
	private UnipointCustomerProfile unipointCustomerProfile;
	private String dateTimeClaimed;
	private Float merchantPointsAdded;
	private Long quantityClaimed;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public OfferClaim() {
	}

	public OfferClaim(long offerClaimId) {
		this.offerClaimId = offerClaimId;
	}

	public OfferClaim(long offerClaimId, MerchantUser merchantUserByLastModifiedByRef,
			MerchantUser merchantUserByAddedByRef, Offer offer, UnipointCustomerProfile unipointCustomerProfile,
			String dateTimeClaimed, Float merchantPointsAdded, Long quantityClaimed, String addedDateTime,
			String lastModifiedDateTime, String lastModifiedFields) {
		this.offerClaimId = offerClaimId;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.offer = offer;
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.dateTimeClaimed = dateTimeClaimed;
		this.merchantPointsAdded = merchantPointsAdded;
		this.quantityClaimed = quantityClaimed;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id

	@Column(name = "offer_claim_id", unique = true, nullable = false)
	public long getOfferClaimId() {
		return this.offerClaimId;
	}

	public void setOfferClaimId(long offerClaimId) {
		this.offerClaimId = offerClaimId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offer_ref_id")
	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unipoint_customer_ref_id")
	public UnipointCustomerProfile getUnipointCustomerProfile() {
		return this.unipointCustomerProfile;
	}

	public void setUnipointCustomerProfile(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	@Column(name = "date_time_claimed", length = 100)
	public String getDateTimeClaimed() {
		return this.dateTimeClaimed;
	}

	public void setDateTimeClaimed(String dateTimeClaimed) {
		this.dateTimeClaimed = dateTimeClaimed;
	}

	@Column(name = "merchant_points_added", precision = 8, scale = 8)
	public Float getMerchantPointsAdded() {
		return this.merchantPointsAdded;
	}

	public void setMerchantPointsAdded(Float merchantPointsAdded) {
		this.merchantPointsAdded = merchantPointsAdded;
	}

	@Column(name = "quantity_claimed")
	public Long getQuantityClaimed() {
		return this.quantityClaimed;
	}

	public void setQuantityClaimed(Long quantityClaimed) {
		this.quantityClaimed = quantityClaimed;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
