package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OfferLeafletId generated by hbm2java
 */
@Embeddable
public class OfferLeafletId implements java.io.Serializable {

	private Long offerId;
	private Long leafletId;
	private Long addedByRef;
	private String addedDateTime;
	private Long lastModifiedByRef;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public OfferLeafletId() {
	}

	public OfferLeafletId(Long offerId, Long leafletId, Long addedByRef, String addedDateTime, Long lastModifiedByRef,
			String lastModifiedDateTime, String lastModifiedFields) {
		this.offerId = offerId;
		this.leafletId = leafletId;
		this.addedByRef = addedByRef;
		this.addedDateTime = addedDateTime;
		this.lastModifiedByRef = lastModifiedByRef;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Column(name = "offerID")
	public Long getOfferId() {
		return this.offerId;
	}

	public void setOfferId(Long offerId) {
		this.offerId = offerId;
	}

	@Column(name = "leafletID")
	public Long getLeafletId() {
		return this.leafletId;
	}

	public void setLeafletId(Long leafletId) {
		this.leafletId = leafletId;
	}

	@Column(name = "added_by_ref")
	public Long getAddedByRef() {
		return this.addedByRef;
	}

	public void setAddedByRef(Long addedByRef) {
		this.addedByRef = addedByRef;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_by_ref")
	public Long getLastModifiedByRef() {
		return this.lastModifiedByRef;
	}

	public void setLastModifiedByRef(Long lastModifiedByRef) {
		this.lastModifiedByRef = lastModifiedByRef;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OfferLeafletId))
			return false;
		OfferLeafletId castOther = (OfferLeafletId) other;

		return ((this.getOfferId() == castOther.getOfferId()) || (this.getOfferId() != null
				&& castOther.getOfferId() != null && this.getOfferId().equals(castOther.getOfferId())))
				&& ((this.getLeafletId() == castOther.getLeafletId()) || (this.getLeafletId() != null
						&& castOther.getLeafletId() != null && this.getLeafletId().equals(castOther.getLeafletId())))
				&& ((this.getAddedByRef() == castOther.getAddedByRef()) || (this.getAddedByRef() != null
						&& castOther.getAddedByRef() != null && this.getAddedByRef().equals(castOther.getAddedByRef())))
				&& ((this.getAddedDateTime() == castOther.getAddedDateTime())
						|| (this.getAddedDateTime() != null && castOther.getAddedDateTime() != null
								&& this.getAddedDateTime().equals(castOther.getAddedDateTime())))
				&& ((this.getLastModifiedByRef() == castOther.getLastModifiedByRef())
						|| (this.getLastModifiedByRef() != null && castOther.getLastModifiedByRef() != null
								&& this.getLastModifiedByRef().equals(castOther.getLastModifiedByRef())))
				&& ((this.getLastModifiedDateTime() == castOther.getLastModifiedDateTime())
						|| (this.getLastModifiedDateTime() != null && castOther.getLastModifiedDateTime() != null
								&& this.getLastModifiedDateTime().equals(castOther.getLastModifiedDateTime())))
				&& ((this.getLastModifiedFields() == castOther.getLastModifiedFields())
						|| (this.getLastModifiedFields() != null && castOther.getLastModifiedFields() != null
								&& this.getLastModifiedFields().equals(castOther.getLastModifiedFields())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOfferId() == null ? 0 : this.getOfferId().hashCode());
		result = 37 * result + (getLeafletId() == null ? 0 : this.getLeafletId().hashCode());
		result = 37 * result + (getAddedByRef() == null ? 0 : this.getAddedByRef().hashCode());
		result = 37 * result + (getAddedDateTime() == null ? 0 : this.getAddedDateTime().hashCode());
		result = 37 * result + (getLastModifiedByRef() == null ? 0 : this.getLastModifiedByRef().hashCode());
		result = 37 * result + (getLastModifiedDateTime() == null ? 0 : this.getLastModifiedDateTime().hashCode());
		result = 37 * result + (getLastModifiedFields() == null ? 0 : this.getLastModifiedFields().hashCode());
		return result;
	}

}
