package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", schema = "unipointmain")
public class Payment implements java.io.Serializable {

	private long paymentid;
	private MerchantUser merchantUser;
	private String payenttype;
	private String paymentdatetime;
	private double amountpaid;
	private String paymentdescription;

	public Payment() {
	}

	public Payment(long paymentid, MerchantUser merchantUser, String paymentdatetime, double amountpaid) {
		this.paymentid = paymentid;
		this.merchantUser = merchantUser;
		this.paymentdatetime = paymentdatetime;
		this.amountpaid = amountpaid;
	}

	public Payment(long paymentid, MerchantUser merchantUser, String payenttype, String paymentdatetime,
			double amountpaid, String paymentdescription) {
		this.paymentid = paymentid;
		this.merchantUser = merchantUser;
		this.payenttype = payenttype;
		this.paymentdatetime = paymentdatetime;
		this.amountpaid = amountpaid;
		this.paymentdescription = paymentdescription;
	}

	@Id

	@Column(name = "paymentid", unique = true, nullable = false)
	public long getPaymentid() {
		return this.paymentid;
	}

	public void setPaymentid(long paymentid) {
		this.paymentid = paymentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_user_ref_id", nullable = false)
	public MerchantUser getMerchantUser() {
		return this.merchantUser;
	}

	public void setMerchantUser(MerchantUser merchantUser) {
		this.merchantUser = merchantUser;
	}

	@Column(name = "payenttype")
	public String getPayenttype() {
		return this.payenttype;
	}

	public void setPayenttype(String payenttype) {
		this.payenttype = payenttype;
	}

	@Column(name = "paymentdatetime", nullable = false, length = 100)
	public String getPaymentdatetime() {
		return this.paymentdatetime;
	}

	public void setPaymentdatetime(String paymentdatetime) {
		this.paymentdatetime = paymentdatetime;
	}

	@Column(name = "amountpaid", nullable = false, precision = 17, scale = 17)
	public double getAmountpaid() {
		return this.amountpaid;
	}

	public void setAmountpaid(double amountpaid) {
		this.amountpaid = amountpaid;
	}

	@Column(name = "paymentdescription")
	public String getPaymentdescription() {
		return this.paymentdescription;
	}

	public void setPaymentdescription(String paymentdescription) {
		this.paymentdescription = paymentdescription;
	}

}
