package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PointRewardType generated by hbm2java
 */
@Entity
@Table(name = "point_reward_type", schema = "unipointmain")
public class PointRewardType implements java.io.Serializable {

	private long rewardTypeId;
	private Merchant merchant;
	private MerchantUser merchantUserByAddedByRef;
	private MerchantUser merchantUserByLastModifiedByRef;
	private String pointRewardTypeDescription;
	private String eligibleSchemes;
	private String dateTimeAdded;
	private Long pointCount;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;
	private Set<PointRewards> pointRewardses = new HashSet<PointRewards>(0);

	public PointRewardType() {
	}

	public PointRewardType(long rewardTypeId) {
		this.rewardTypeId = rewardTypeId;
	}

	public PointRewardType(long rewardTypeId, Merchant merchant, MerchantUser merchantUserByAddedByRef,
			MerchantUser merchantUserByLastModifiedByRef, String pointRewardTypeDescription, String eligibleSchemes,
			String dateTimeAdded, Long pointCount, String addedDateTime, String lastModifiedDateTime,
			String lastModifiedFields, Set<PointRewards> pointRewardses) {
		this.rewardTypeId = rewardTypeId;
		this.merchant = merchant;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.pointRewardTypeDescription = pointRewardTypeDescription;
		this.eligibleSchemes = eligibleSchemes;
		this.dateTimeAdded = dateTimeAdded;
		this.pointCount = pointCount;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
		this.pointRewardses = pointRewardses;
	}

	@Id

	@Column(name = "reward_type_id", unique = true, nullable = false)
	public long getRewardTypeId() {
		return this.rewardTypeId;
	}

	public void setRewardTypeId(long rewardTypeId) {
		this.rewardTypeId = rewardTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_ref_id")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@Column(name = "point_reward_type_description")
	public String getPointRewardTypeDescription() {
		return this.pointRewardTypeDescription;
	}

	public void setPointRewardTypeDescription(String pointRewardTypeDescription) {
		this.pointRewardTypeDescription = pointRewardTypeDescription;
	}

	@Column(name = "eligible_schemes")
	public String getEligibleSchemes() {
		return this.eligibleSchemes;
	}

	public void setEligibleSchemes(String eligibleSchemes) {
		this.eligibleSchemes = eligibleSchemes;
	}

	@Column(name = "date_time_added")
	public String getDateTimeAdded() {
		return this.dateTimeAdded;
	}

	public void setDateTimeAdded(String dateTimeAdded) {
		this.dateTimeAdded = dateTimeAdded;
	}

	@Column(name = "point_count")
	public Long getPointCount() {
		return this.pointCount;
	}

	public void setPointCount(Long pointCount) {
		this.pointCount = pointCount;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pointRewardType")
	public Set<PointRewards> getPointRewardses() {
		return this.pointRewardses;
	}

	public void setPointRewardses(Set<PointRewards> pointRewardses) {
		this.pointRewardses = pointRewardses;
	}

}
