package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "unipointmain")
public class Product implements java.io.Serializable {

	private long productid;
	private Catagory catagory;
	private MerchantUser merchantUserByAddedbyRefId;
	private MerchantUser merchantUserByLastModifiedByRef;
	private MerchantUser merchantUserByAddedByRef;
	private String code;
	private String description;
	private String startingnumber;
	private String endingnumber;
	private String lastdateused;
	private String lastnoused;
	private String locationcode;
	private BigDecimal quantityavailable;
	private Double unitprice;
	private String productName;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public Product() {
	}

	public Product(long productid) {
		this.productid = productid;
	}

	public Product(long productid, Catagory catagory, MerchantUser merchantUserByAddedbyRefId,
			MerchantUser merchantUserByLastModifiedByRef, MerchantUser merchantUserByAddedByRef, String code,
			String description, String startingnumber, String endingnumber, String lastdateused, String lastnoused,
			String locationcode, BigDecimal quantityavailable, Double unitprice, String productName,
			String addedDateTime, String lastModifiedDateTime, String lastModifiedFields) {
		this.productid = productid;
		this.catagory = catagory;
		this.merchantUserByAddedbyRefId = merchantUserByAddedbyRefId;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.code = code;
		this.description = description;
		this.startingnumber = startingnumber;
		this.endingnumber = endingnumber;
		this.lastdateused = lastdateused;
		this.lastnoused = lastnoused;
		this.locationcode = locationcode;
		this.quantityavailable = quantityavailable;
		this.unitprice = unitprice;
		this.productName = productName;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id

	@Column(name = "productid", unique = true, nullable = false)
	public long getProductid() {
		return this.productid;
	}

	public void setProductid(long productid) {
		this.productid = productid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_product_category_id")
	public Catagory getCatagory() {
		return this.catagory;
	}

	public void setCatagory(Catagory catagory) {
		this.catagory = catagory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "addedby_ref_id")
	public MerchantUser getMerchantUserByAddedbyRefId() {
		return this.merchantUserByAddedbyRefId;
	}

	public void setMerchantUserByAddedbyRefId(MerchantUser merchantUserByAddedbyRefId) {
		this.merchantUserByAddedbyRefId = merchantUserByAddedbyRefId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@Column(name = "code", length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "startingnumber", length = 100)
	public String getStartingnumber() {
		return this.startingnumber;
	}

	public void setStartingnumber(String startingnumber) {
		this.startingnumber = startingnumber;
	}

	@Column(name = "endingnumber", length = 100)
	public String getEndingnumber() {
		return this.endingnumber;
	}

	public void setEndingnumber(String endingnumber) {
		this.endingnumber = endingnumber;
	}

	@Column(name = "lastdateused", length = 100)
	public String getLastdateused() {
		return this.lastdateused;
	}

	public void setLastdateused(String lastdateused) {
		this.lastdateused = lastdateused;
	}

	@Column(name = "lastnoused", length = 100)
	public String getLastnoused() {
		return this.lastnoused;
	}

	public void setLastnoused(String lastnoused) {
		this.lastnoused = lastnoused;
	}

	@Column(name = "locationcode")
	public String getLocationcode() {
		return this.locationcode;
	}

	public void setLocationcode(String locationcode) {
		this.locationcode = locationcode;
	}

	@Column(name = "quantityavailable", precision = 131089, scale = 0)
	public BigDecimal getQuantityavailable() {
		return this.quantityavailable;
	}

	public void setQuantityavailable(BigDecimal quantityavailable) {
		this.quantityavailable = quantityavailable;
	}

	@Column(name = "unitprice", precision = 17, scale = 17)
	public Double getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(Double unitprice) {
		this.unitprice = unitprice;
	}

	@Column(name = "product_name")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
