package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubmittedFeedback generated by hbm2java
 */
@Entity
@Table(name = "submitted_feedback", schema = "unipointmain")
public class SubmittedFeedback implements java.io.Serializable {

	private long subFedbkId;
	private MerchantFeedback merchantFeedback;
	private Long fkMerchantCustomerId;

	public SubmittedFeedback() {
	}

	public SubmittedFeedback(long subFedbkId) {
		this.subFedbkId = subFedbkId;
	}

	public SubmittedFeedback(long subFedbkId, MerchantFeedback merchantFeedback, Long fkMerchantCustomerId) {
		this.subFedbkId = subFedbkId;
		this.merchantFeedback = merchantFeedback;
		this.fkMerchantCustomerId = fkMerchantCustomerId;
	}

	@Id

	@Column(name = "sub_fedbk_id", unique = true, nullable = false)
	public long getSubFedbkId() {
		return this.subFedbkId;
	}

	public void setSubFedbkId(long subFedbkId) {
		this.subFedbkId = subFedbkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feedback_ref_id")
	public MerchantFeedback getMerchantFeedback() {
		return this.merchantFeedback;
	}

	public void setMerchantFeedback(MerchantFeedback merchantFeedback) {
		this.merchantFeedback = merchantFeedback;
	}

	@Column(name = "fk_merchant_customer_id")
	public Long getFkMerchantCustomerId() {
		return this.fkMerchantCustomerId;
	}

	public void setFkMerchantCustomerId(Long fkMerchantCustomerId) {
		this.fkMerchantCustomerId = fkMerchantCustomerId;
	}

}
