package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SubscribeMerchant generated by hbm2java
 */
@Entity
@Table(name = "subscribe_merchant", schema = "unipointmain")
public class SubscribeMerchant implements java.io.Serializable {

	private long subscriptionid;
	private Merchant merchant;
	private MerchantUser merchantUserByLastModifiedByRef;
	private MerchantUser merchantUserByAddedByRef;
	private UnipointCustomerProfile unipointCustomerProfile;
	private String datetime;
	private BigDecimal totalpoints;
	private Double redeemablepoints;
	private String expirydate;
	private String qrcode;
	private Integer schemerefid;
	private String enabled;
	private String cardnumber;
	private String registereddevice;
	private String latlongregistered;
	private Integer currentoffercount;
	private Boolean isSubscribed;
	private Boolean isFollowing;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public SubscribeMerchant() {
	}

	public SubscribeMerchant(long subscriptionid) {
		this.subscriptionid = subscriptionid;
	}

	public SubscribeMerchant(long subscriptionid, Merchant merchant, MerchantUser merchantUserByLastModifiedByRef,
			MerchantUser merchantUserByAddedByRef, UnipointCustomerProfile unipointCustomerProfile, String datetime,
			BigDecimal totalpoints, Double redeemablepoints, String expirydate, String qrcode, Integer schemerefid,
			String enabled, String cardnumber, String registereddevice, String latlongregistered,
			Integer currentoffercount, Boolean isSubscribed, Boolean isFollowing, String addedDateTime,
			String lastModifiedDateTime, String lastModifiedFields) {
		this.subscriptionid = subscriptionid;
		this.merchant = merchant;
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.datetime = datetime;
		this.totalpoints = totalpoints;
		this.redeemablepoints = redeemablepoints;
		this.expirydate = expirydate;
		this.qrcode = qrcode;
		this.schemerefid = schemerefid;
		this.enabled = enabled;
		this.cardnumber = cardnumber;
		this.registereddevice = registereddevice;
		this.latlongregistered = latlongregistered;
		this.currentoffercount = currentoffercount;
		this.isSubscribed = isSubscribed;
		this.isFollowing = isFollowing;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id
	@SequenceGenerator(name="pk_sequence",sequenceName="unipointmain.cus_subm_pk_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
	@Column(name = "subscriptionid", unique = true, nullable = false)
	public long getSubscriptionid() {
		return this.subscriptionid;
	}

	public void setSubscriptionid(long subscriptionid) {
		this.subscriptionid = subscriptionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_ref_id")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_modified_by_ref")
	public MerchantUser getMerchantUserByLastModifiedByRef() {
		return this.merchantUserByLastModifiedByRef;
	}

	public void setMerchantUserByLastModifiedByRef(MerchantUser merchantUserByLastModifiedByRef) {
		this.merchantUserByLastModifiedByRef = merchantUserByLastModifiedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "added_by_ref")
	public MerchantUser getMerchantUserByAddedByRef() {
		return this.merchantUserByAddedByRef;
	}

	public void setMerchantUserByAddedByRef(MerchantUser merchantUserByAddedByRef) {
		this.merchantUserByAddedByRef = merchantUserByAddedByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unipoint_customer_ref_id")
	public UnipointCustomerProfile getUnipointCustomerProfile() {
		return this.unipointCustomerProfile;
	}

	public void setUnipointCustomerProfile(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	@Column(name = "datetime", length = 50)
	public String getDatetime() {
		return this.datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	@Column(name = "totalpoints", precision = 131089, scale = 0)
	public BigDecimal getTotalpoints() {
		return this.totalpoints;
	}

	public void setTotalpoints(BigDecimal totalpoints) {
		this.totalpoints = totalpoints;
	}

	@Column(name = "redeemablepoints", precision = 17, scale = 17)
	public Double getRedeemablepoints() {
		return this.redeemablepoints;
	}

	public void setRedeemablepoints(Double redeemablepoints) {
		this.redeemablepoints = redeemablepoints;
	}

	@Column(name = "expirydate", length = 50)
	public String getExpirydate() {
		return this.expirydate;
	}

	public void setExpirydate(String expirydate) {
		this.expirydate = expirydate;
	}

	@Column(name = "qrcode")
	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	@Column(name = "schemerefid")
	public Integer getSchemerefid() {
		return this.schemerefid;
	}

	public void setSchemerefid(Integer schemerefid) {
		this.schemerefid = schemerefid;
	}

	@Column(name = "enabled", length = 5)
	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	@Column(name = "cardnumber")
	public String getCardnumber() {
		return this.cardnumber;
	}

	public void setCardnumber(String cardnumber) {
		this.cardnumber = cardnumber;
	}

	@Column(name = "registereddevice", length = 100)
	public String getRegistereddevice() {
		return this.registereddevice;
	}

	public void setRegistereddevice(String registereddevice) {
		this.registereddevice = registereddevice;
	}

	@Column(name = "latlongregistered", length = 100)
	public String getLatlongregistered() {
		return this.latlongregistered;
	}

	public void setLatlongregistered(String latlongregistered) {
		this.latlongregistered = latlongregistered;
	}

	@Column(name = "currentoffercount")
	public Integer getCurrentoffercount() {
		return this.currentoffercount;
	}

	public void setCurrentoffercount(Integer currentoffercount) {
		this.currentoffercount = currentoffercount;
	}

	@Column(name = "is_subscribed")
	public Boolean getIsSubscribed() {
		return this.isSubscribed;
	}

	public void setIsSubscribed(Boolean isSubscribed) {
		this.isSubscribed = isSubscribed;
	}

	@Column(name = "is_following")
	public Boolean getIsFollowing() {
		return this.isFollowing;
	}

	public void setIsFollowing(Boolean isFollowing) {
		this.isFollowing = isFollowing;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}



}
