package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UnipointcustomerAdvanced generated by hbm2java
 */
@Entity
@Table(name = "unipointcustomer_advanced", schema = "unipointmain")
public class UnipointcustomerAdvanced implements java.io.Serializable {

	private long unipointCustomerId;
	private UnipointCustomerProfile unipointCustomerProfile;
	private String registeredlocation;
	private String registeredip;
	private String registeredmac;
	private String contactlist;
	private String followingbrands;
	private String favorites;
	private BigDecimal followercount;

	public UnipointcustomerAdvanced() {
	}

	public UnipointcustomerAdvanced(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	public UnipointcustomerAdvanced(UnipointCustomerProfile unipointCustomerProfile, String registeredlocation,
			String registeredip, String registeredmac, String contactlist, String followingbrands, String favorites,
			BigDecimal followercount) {
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.registeredlocation = registeredlocation;
		this.registeredip = registeredip;
		this.registeredmac = registeredmac;
		this.contactlist = contactlist;
		this.followingbrands = followingbrands;
		this.favorites = favorites;
		this.followercount = followercount;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "unipointCustomerProfile"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "unipoint_customer_id", unique = true, nullable = false)
	public long getUnipointCustomerId() {
		return this.unipointCustomerId;
	}

	public void setUnipointCustomerId(long unipointCustomerId) {
		this.unipointCustomerId = unipointCustomerId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UnipointCustomerProfile getUnipointCustomerProfile() {
		return this.unipointCustomerProfile;
	}

	public void setUnipointCustomerProfile(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	@Column(name = "registeredlocation")
	public String getRegisteredlocation() {
		return this.registeredlocation;
	}

	public void setRegisteredlocation(String registeredlocation) {
		this.registeredlocation = registeredlocation;
	}

	@Column(name = "registeredip", length = 100)
	public String getRegisteredip() {
		return this.registeredip;
	}

	public void setRegisteredip(String registeredip) {
		this.registeredip = registeredip;
	}

	@Column(name = "registeredmac", length = 100)
	public String getRegisteredmac() {
		return this.registeredmac;
	}

	public void setRegisteredmac(String registeredmac) {
		this.registeredmac = registeredmac;
	}

	@Column(name = "contactlist")
	public String getContactlist() {
		return this.contactlist;
	}

	public void setContactlist(String contactlist) {
		this.contactlist = contactlist;
	}

	@Column(name = "followingbrands")
	public String getFollowingbrands() {
		return this.followingbrands;
	}

	public void setFollowingbrands(String followingbrands) {
		this.followingbrands = followingbrands;
	}

	@Column(name = "favorites")
	public String getFavorites() {
		return this.favorites;
	}

	public void setFavorites(String favorites) {
		this.favorites = favorites;
	}

	@Column(name = "followercount", precision = 131089, scale = 0)
	public BigDecimal getFollowercount() {
		return this.followercount;
	}

	public void setFollowercount(BigDecimal followercount) {
		this.followercount = followercount;
	}

}
