package com.unipoint.model;
// Generated Oct 18, 2016 4:59:22 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Wishlist generated by hbm2java
 */
@Entity
@Table(name = "wishlist", schema = "unipointmain")
public class Wishlist implements java.io.Serializable {

	private long wishlistid;
	private Offer offer;
	private UnipointCustomerProfile unipointCustomerProfile;
	private Long description;
	private String datetime;
	private String expirydate;
	private String expirytime;
	private String buzzedme;
	private String checked;
	private Boolean enabled;
	private String addedDateTime;
	private String lastModifiedDateTime;
	private String lastModifiedFields;

	public Wishlist() {
	}

	public Wishlist(long wishlistid) {
		this.wishlistid = wishlistid;
	}

	public Wishlist(long wishlistid, Offer offer, UnipointCustomerProfile unipointCustomerProfile, Long description,
			String datetime, String expirydate, String expirytime, String buzzedme, String checked, Boolean enabled,
			String addedDateTime, String lastModifiedDateTime, String lastModifiedFields) {
		this.wishlistid = wishlistid;
		this.offer = offer;
		this.unipointCustomerProfile = unipointCustomerProfile;
		this.description = description;
		this.datetime = datetime;
		this.expirydate = expirydate;
		this.expirytime = expirytime;
		this.buzzedme = buzzedme;
		this.checked = checked;
		this.enabled = enabled;
		this.addedDateTime = addedDateTime;
		this.lastModifiedDateTime = lastModifiedDateTime;
		this.lastModifiedFields = lastModifiedFields;
	}

	@Id

	@Column(name = "wishlistid", unique = true, nullable = false)
	public long getWishlistid() {
		return this.wishlistid;
	}

	public void setWishlistid(long wishlistid) {
		this.wishlistid = wishlistid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offer_ref_id")
	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unipoint_customer_ref_id")
	public UnipointCustomerProfile getUnipointCustomerProfile() {
		return this.unipointCustomerProfile;
	}

	public void setUnipointCustomerProfile(UnipointCustomerProfile unipointCustomerProfile) {
		this.unipointCustomerProfile = unipointCustomerProfile;
	}

	@Column(name = "description")
	public Long getDescription() {
		return this.description;
	}

	public void setDescription(Long description) {
		this.description = description;
	}

	@Column(name = "datetime", length = 50)
	public String getDatetime() {
		return this.datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	@Column(name = "expirydate", length = 50)
	public String getExpirydate() {
		return this.expirydate;
	}

	public void setExpirydate(String expirydate) {
		this.expirydate = expirydate;
	}

	@Column(name = "expirytime", length = 50)
	public String getExpirytime() {
		return this.expirytime;
	}

	public void setExpirytime(String expirytime) {
		this.expirytime = expirytime;
	}

	@Column(name = "buzzedme", length = 5)
	public String getBuzzedme() {
		return this.buzzedme;
	}

	public void setBuzzedme(String buzzedme) {
		this.buzzedme = buzzedme;
	}

	@Column(name = "checked", length = 5)
	public String getChecked() {
		return this.checked;
	}

	public void setChecked(String checked) {
		this.checked = checked;
	}

	@Column(name = "enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "added_date_time", length = 50)
	public String getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(String addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "last_modified_date_time", length = 50)
	public String getLastModifiedDateTime() {
		return this.lastModifiedDateTime;
	}

	public void setLastModifiedDateTime(String lastModifiedDateTime) {
		this.lastModifiedDateTime = lastModifiedDateTime;
	}

	@Column(name = "last_modified_fields")
	public String getLastModifiedFields() {
		return this.lastModifiedFields;
	}

	public void setLastModifiedFields(String lastModifiedFields) {
		this.lastModifiedFields = lastModifiedFields;
	}

}
